### ISSUE TITLE
getting error 'TypeError: Cannot read property 'folder' of undefined' after following steps given by you.

### ISSUE THREAD

**Issue by govind413** [kushmangal/Nightwatch-Allure-Reporter#2]

**Comment by metaum** [comment]
same issue !

**Comment by kushmangal** [comment]
Can you check if the issue persists in the newer version?

**Comment by metaum** [comment]
I've checked. Now I see the same type of error, but with  another property 
` TypeError: Cannot read property 'sendData' of undefined
`

**Comment by metaum** [comment]
@kushmangal

**Comment by metaum** [comment]
Any thoughts?

**Comment by kushmangal** [comment]
Will check and get back to you

**Comment by kushmangal** [comment]
Hey, just checked. It was due to incorrect code in ReadMe. Also have added another check condition. So try using the new globals file code i.e.
`
const allureReporter = require('nightwatch-allure');
module.exports = {
  reporter: (results,done)=>{
    const reporter = new allureReporter.NightwatchAllureReporter({});
    reporter.write(results,done);
  }
};
`
Also update your package to 1.2.0

**Comment by metaum** [comment]
ok, got it, I'll check it right now!

**Comment by metaum** [comment]
It works, thank you!
